name: studio_podcast_pab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0 
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  image_picker: ^1.1.2
  table_calendar: ^3.1.2

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Icon.jpeg"
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/images/Logo_FEB.jpeg"
  min_sdk_android: 21 

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/Background_FEB.jpeg
    - assets/images/Background_FEB1.jpeg
    - assets/images/Logo_FEB.jpeg
    - assets/images/Icon.jpeg
    - assets/images/Opening_FEB.jpeg
    - assets/images/Opening_FEB1.jpeg